#!/bin/bash

# Full JSON path
JSON_FILE="/var/log/update_declarations.json"

result=$(jq -r '."softwareupdate.pending-version" | .["target-local-date-time"]' "$JSON_FILE")

echo "<result>$result</result>" 
